language: python

python:
 - "2.7"
 - "3.2"

env:
- DJANGO=1.6 DB=postgres

 # command to install dependencies
install:
- pip install -q Django=$DJANGO 
#- pip install -r requirements.txt 

# command to run tests
script: python manage.py test
